### ISSUE TITLE
URLError/SSLCertVerificationError

### ISSUE THREAD

**Issue by NHL-B** [tropycal/tropycal#140] opened 2021-10-14 08:17 UTC
Hello!
I tried again and it still not working... I can't plot hurricane track because of **URLError/SSLCertVerificationError**. Idk if someone had these errors before but it's quite nerve racking. I would be happy if you can help me. @tomerburg @splillo 
Thanks :)

![tropy](https://user-images.githubusercontent.com/92443490/137277316-ca03788e-5638-48ee-a7b5-6eab53844317.jpg)

**Comment by tomerburg** [comment] 2021-10-14 08:39
As I said with the previous issue, this is not a bug with Tropycal but an unrelated upstream issue, or perhaps related to your environment. As such, I am again closing this issue — if this persists, please open a thread in the “discussion” tab, including a full trace back error (copy and paste the *full* error message that python outputs, as this screenshot doesn’t contain enough information to trace back the error).

**Closed by tomerburg** 2021-10-14 08:39 UTC

**Comment by NHL-B** [comment] 2021-10-14 15:38
'atlantic_url='C:/Users/belgherz/.spyder-py3/HURDAT22021.html'

Previous code can't work ? 

I'll try with the .txt you sent file but does it mean that I have to download every time a new .txt file to have update data? if it works... If so can you tell me how to do that without make a 2 hours copy past. 
Thanks again

**Comment by tomerburg** [comment] 2021-10-14 18:06
The second URL I sent you updates about once a year, so this link I sent will be good for the remainder of this year once you save it locally and read it in using the “atlantic_url” argument. NHC has a link to the latest HURDAT file here: https://www.nhc.noaa.gov/data/#hurdat

**Comment by tomerburg** [comment] 2021-10-14 18:37
Hopefully this set of very specific instructions will help:

- Download the file "https://www.nhc.noaa.gov/data/hurdat/hurdat2-1851-2020-052921.txt" and save it to your computer. Let's say hypothetically you save it in a directory such that the full file path is "C:/Users/User/Desktop/hurdat2-1851-2020-052921.txt".
- Open it in tropycal using the full file path and the name of the file that was saved -- in this case that name is "hurdat2-1851-2020-052921.txt" as you can tell from the link above:
`basin = tracks.TrackDataset(atlantic_url="C:/Users/User/Desktop/hurdat2-1851-2020-052921.txt")`

This will allow you to use TrackDataset as specified in the documentation (https://tropycal.github.io/tropycal/api/generated/tropycal.tracks.TrackDataset.html#tropycal.tracks.TrackDataset).

You will likely not be able to use current storms in your current configuration, as it appears that your computer is unable to access the remote NHC server, nor will you be able to make full use of Storm objects (plotting should still be able to work as long as you have all dependencies such as Cartopy and Matplotlib successfully installed).

**Comment by NHL-B** [comment] 2021-10-14 19:01
Thank you so much for your explanations. I will keep you posted. Hopefully it will work this time. Also Excuse my low-level in coding but I just started to use python a week ago and Tropycal just gave me the motivation to do so. It took more than 20 years for me to finally be interested in coding.

**Comment by NHL-B** [comment] 2021-10-15 13:31
Finally, thanks for the help, appreciated that.
![image](https://user-images.githubusercontent.com/92443490/137495085-39623fd2-634b-4599-afc7-53dc0cae9cd4.png)
